### ISSUE TITLE
Issue in reading 1.67 GB files

### ISSUE THREAD

**Issue by halima1993** [MagicForrest/DGVMTools#15]
I am having difficulty to read data from disk that is of the size  1.67GB using `getField()` function.
Because when I read my data with getField() it takes approx 30-50 mintutes and the laptop screen goes black. But the files that are of 949MB are perfectly read by getField() function, however I am having a problem with those files that are of 1.67GB.  I have tried running the code on two different laptops that have a RAM of 4GB and 8GB.

**Comment by MagicForrest** [comment]
Hi Halima, thanks for using DGVMTools and thanks for reporting!  This is the first issue from a completely external person, hopefully I can solve it!  I still feel like it is related to memory requirements, I think I need a little bit more information.  

1. What operating system are you using?  And is it 64 bit?
2. Can you open the file using another function in R, for example read.table? (this might be slow bit it should work eventually)
3. Can you monitor the memory usage when you try to open the file in, for example Task Manager in Windows or the 'top' or 'htop' command in Linux.  Let me know what you see.
4. Could you post the first few lines of the file here?

I have opened LPJ-GUESS files which are many gigabytes before.  It has never been a problem unless my computer has insufficient RAM, that is why I think it might be RAM.

**Comment by halima1993** [comment]
Hello! I will try my best to provide the information required by your question:
1) Both of my laptops are of 64 bit and have windows 10 installed in them.
2)I recently found a function that reads my file that are of 1.67GB sucessfully. I downloaded the package called data.table and used this: data.table::fread("mnee.out",header=T). 
note:"mnee.out" is the output filename that I am trying to read.
3) I cannot even open the task manager when the 'getField' code is being run as the arrow of my laptop gets stuck. Hence I power off my laptop by the power button purposefully in order to restart.
4)First few lines of one of my files is(note: I copied from Microsoft Excel):

Lon | Lat | Year | BNE | BINE | BNS | TeBS | IBS | TeBE | TrBE | TrIBE | TrBR | C3G | C4G | Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
61 | 37 | 1850 | 0 | 0 | 0 | 0.004 | 0.004 | 0.017 | 0 | 0 | 0 | 0.167 | 0 | 0.192
61 | 37 | 1851 | 0 | 0 | 0 | 0.006 | 0.006 | 0.024 | 0 | 0 | 0 | 0.17 | 0 | 0.206
61 | 37 | 1852 | 0 | 0 | 0 | 0.001 | 0.001 | -0.002 | 0 | 0 | 0 | 0.112 | 0 | 0.112
61 | 37 | 1853 | 0 | 0 | 0 | 0 | 0.001 | 0.012 | 0 | 0 | 0 | 0.083 | 0 | 0.096
61 | 37 | 1854 | 0 | 0 | 0 | 0.002 | 0.002 | 0.007 | 0 | 0 | 0 | 0.125 | 0 | 0.136
61 | 37 | 1855 | 0 | 0 | 0 | 0.004 | 0.005 | 0.023 | 0 | 0 | 0 | 0.161 | 0 | 0.193
61 | 37 | 1856 | 0 | 0 | 0 | 0.004 | 0.005 | 0.028 | 0 | 0 | 0 | 0.174 | 0 | 0.212
61 | 37 | 1857 | 0 | 0 | 0 | 0.002 | 0.003 | 0.017 | 0 | 0 | 0 | 0.143 | 0 | 0.165
61 | 37 | 1858 | 0 | 0 | 0 | 0 | 0 | -0.007 | 0 | 0 | 0 | 0.119 | 0 | 0.111
61 | 37 | 1859 | 0 | 0 | 0 | 0 | 0 | 0.007 | 0 | 0 | 0 | 0.138 | 0 | 0.145
61 | 37 | 1860 | 0 | 0 | 0 | 0.001 | 0.001 | 0.019 | 0 | 0 | 0 | 0.146 | 0 | 0.167
61 | 37 | 1861 | 0 | 0 | 0 | 0.001 | 0.001 | 0.017 | 0 | 0 | 0 | 0.128 | 0 | 0.147
61 | 37 | 1862 | 0 | 0 | 0 | 0.001 | 0.001 | 0.001 | 0 | 0 | 0 | 0.109 | 0 | 0.111

Note: Total number of rows are 675692
If there is any confusion in my answer, I will clarify it further.
Thank you!

**Comment by MagicForrest** [comment]
Hi Halima, thanks for the further info.  It is very interesting that you can read the file using data.table::fread, because that is exactly the function that DGVMTools uses to read the data!  So it is a real mystery as to why it works outside the package but not inside.  The only difference is that I don't use "header=T".  Could you test without "header=T" please?

And perhaps it would be good if I could examine/test your mnee.out file.  Do you have any file sharing possibilities?  If you zip the file it will be get very much smaller and easier to transfer.

**Comment by MagicForrest** [comment]
And another thing question.  Do you have a problem with all the monthly files (eg also mnpp.out, mgpp.out, mswcont_upper.out etc), or just mnee.out?

**Comment by halima1993** [comment]
Hello!

I have zipped the mnee.out file and is of 271MB. But it can't be dragged into this website of github and shows the message"That's a big file. Try again with a file smaller than 10MB". I have problem reading files that are of 1.67GB that are mnee.out, mgpp.out, mnpp.out and anpp.out. The rest are of 949MB and are perfectly read by the getfield() function that are cflux.out and cmass.out.  

And can you please refer to me the code which I should use without header=T which you mentioned earlier? Because I am a bit confused. Should I use data.table::fread without inserting header=T ? Or should I use getfield() function?This is how I use the getfield() function which fails to work:
`GUESS.run1 <- defineSource(id = "ccsm4_26_c3_1_1",
                          dir = "C:/Users/MY PC/Documents/ccsm4_26_c3_1_1", # this would normlly just be a character string containing a path
                          format = GUESS,
                          name = "ccsm4 RCP 2.6")`
`mnee.full <- getField(source = GUESS.run1, 
                     var = "mnee")`

Is there any other means I can share my file with you?Perhaps through Onedrive?

(Basically each file contain global data on each variable( worldwide), and I am required to crop it using my shapefile of South Asia that is the study area to carry out further anaylsis )

**Comment by MagicForrest** [comment]
Yes, I meant try the data.table::fread command without "header=T".  Although I don't think it will be make any difference.  Could you also try 

 `mnee.full <- getField(source = GUESS.run1, var = "mnee", verbose = TRUE)`

and tell me if you see the head of the data.table printed before the screen goes blank.

I am still think it is a memory size but I have some ideas on how to fix it ;-)   Maybe you could test with:

 `mnee.full <- getField(source = GUESS.run1, var = "mnee", verbose = TRUE, first.year = 1850, last.year = 1851)`

I would still like to test with you file.  I don't use Onedrive, but it might provide you with a download link that you can give me.  Dropbox and box.com are also free alternatives that work.    I would also be interested in testing with your shapefile of South Asia.  If you can transfer me that it might also help.

**Comment by halima1993** [comment]
Greetings!
As you mentioned the code above: 
`mnee.full <- getField(source = GUESS.run1, var = "mnee", verbose = TRUE)`
1) I definitely see the head of the data.table printed before the screen goes blank.

2)and the second code you mentioned
`mnee.full <- getField(source = GUESS.run1, var = "mnee", verbose = TRUE, first.year = 1850, last.year = 1851)`
This code works and I get plots using plotTemporal, which I am looking for. But as I mentioned this is global data and when I crop using South Asia shapefile, and then try aggregateSpatial and afterwards plot temporal it gives numerous errors. 

3)Moreover,
`mnee.full <- getField(source = GUESS.run1, var = "mnee", verbose = TRUE, first.year = 1850, last.year = 2100)`
I also tried this code (setting last.year=2100), this doesnt work and the computer screen goes black after few minutes.
4) I agree it will be easy If you get the file and shapefile. I will be able to transfer the files through Dropbox. In order to share it kindly let me know which email should I use to send it you. 
5)If the issue is rising due to memory shortage then what do you recommend how much RAM should a laptop have in order to read these files?

**Comment by MagicForrest** [comment]
Okay, it really looks like a memory size issue.  It seems to occur when the package 'melts' the data into a format of one row per month, instead of one row per year.  This is a more logical format in which to store the data, but takes up more space. I have a couple of possible fixes in mind.  About how much memory you need,  I hope that 4 Gb should be enough, but 8 Gb should definitely be enough.

Yes, send the dropbox invitation to my senckenberg account, the one you originally contacted me on.

**Comment by halima1993** [comment]
As I mentioned earlier, I have two laptops in which I am currently working on. One is of 4GB RAM and the other is of 8GB RAM. However the code fails to work in both of them. Ok I will share via Dropbox.

**Comment by MagicForrest** [comment]
Hi Halima,
Thanks for the files.  I can confirm that it is definitely a memory issue.  The package can read the full file okay, but it fails when I `melt` the data.table into the 'long table' format used internally by DGVMTools.  In the short term I am working on a solution where you can directly specify a shapefile (in your case the South East Asia one) when you call `getField()` and hence immediately reducing the size of the data.  Hopefully I can give you a new version next week for testing it out.  However, that isn't a general solution to the problem, so that is something I will think about longer term.

**Comment by MagicForrest** [comment]
Hi again Halima, 

I have a solution that just might work! As I mentioned before, the idea is that you can supply the shapefile at the getField() function call which means that it crops away all the data that you don't want (so it doesn't take up so much memory).  Try out the following attached test script (you will have to change the paths for your system):

[test_Halima_upload.R.zip](https://github.com/MagicForrest/DGVMTools/files/2807955/test_Halima_upload.R.zip)

On my computer I think the maximum memory use is just under 8Gb, so try on your 8Gb laptop.  If it still doesn't work I have another optimisation in mind, but it will take a bit longer to implement.  

Let me know how it goes!

**Comment by halima1993** [comment]
Hello!

I tired out the script you provided and it works well =D! It does take 35-45 minutes for the getField() to run, but it eventually does work. Thank you so much. I will test it with other of my files as well! Thanks again!

**Comment by halima1993** [comment]
Ok Thank you! Yes you may close it=). Thanks for the help!
