### ISSUE TITLE
exporting the maps into raster format

### ISSUE THREAD

**Issue by sedrickel** [MagicForrest/DGVMTools#20]
Hi Matthew,

Is there a way at the moment to export rasters from the biome classifications (or from other plotSpatial outputs) that DGVM Tools creates? 

(I created a separate thread as this is a different issue...)

Thanks! :)

**Comment by MagicForrest** [comment]
Yes, different thread different issue is good!

There is functionality to do this, but you export Fields not plots (so ecport the objects you get from geField() or getBiomes(), not from plotSpatial()).  Do something like:

`biome.as.raster <- as.Raster(model.biomes)`

This converts them to an R raster object.   See also `?DGVMTools::as.Raster` for more details.

Is this what you wanted?  Or did you want to write the files to disk as a netCDF or GeoTiff or something?

**Comment by sedrickel** [comment]
That solved it. Thanks!
