### ISSUE TITLE
discontinuous map when plotting mean height in aDGVM2 

### ISSUE THREAD

**Issue by sedrickel** [MagicForrest/DGVMTools#21]
Hello again, 

So right now I am trying to map out mean canopy height for our results. When I use adgvm.scheme = 2 (trait files reading) in the getField command (var = meanheight), I get a discontinuous map with higher (and the correct) values, with max around 15 m. When I use adgvm.scheme =1 (pop files reading), I then get a continuous map which is what we want, but with much lower values at around 5m because it averages the shrubs with the trees. Any idea why DGVMTools is showing the discontinuous maps in scheme 2? Could it be that NA's are being included in the averaging, then creating NA pixels? 

I attached the photos of the plotSpatial results below. Thanks!!

![adgvm1-htsample](https://user-images.githubusercontent.com/47240789/52987256-5ece4c00-3435-11e9-90db-dcc594fc6b7b.png)
![adgvm2-htsample](https://user-images.githubusercontent.com/47240789/52987257-5f66e280-3435-11e9-969f-a1efe5a77187.png)

**Comment by sscheiter** [comment]
This was caused by divisions by zero in the getQuantity_aDGVM_Scheme2 function and it is fixed now.

**Comment by sedrickel** [comment]
Thank you Simon for the fix! Closing this now.
