### ISSUE TITLE
After I updated R to 3.6, I get errors when installing the package (Windows)

### ISSUE THREAD

**Issue by antonycastro** [MagicForrest/DGVMTools#27]
After I updated my R to 3.6, I keep getting the following error when installing the package. Any idea how could I solve this?

> remotes::install_github("MagicForrest/DGVMTools")
Downloading GitHub repo MagicForrest/DGVMTools@master
√  checking for file 'C:\Users\Tony\AppData\Local\Temp\RtmpumyjeA\remotes541450ba4878\MagicForrest-DGVMTools-6bca4dd/DESCRIPTION' (1.3s)
-  preparing 'DGVMTools': (2.3s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (949ms)
-  checking for empty or unneeded directories
-  building 'DGVMTools_0.8.1.tar.gz'
   
Installing package into ‘C:/Users/Tony/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'DGVMTools' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  : 
  The prototype for class "Source" has undefined slot(s): 'lonlat.offset1', 'lonlat.offset2'
Error: unable to load R code in package 'DGVMTools'
Execution halted
ERROR: lazy loading failed for package 'DGVMTools'
* removing 'C:/Users/Tony/Documents/R/win-library/3.6/DGVMTools'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Tony/AppData/Local/Temp/RtmpumyjeA/file541472924862/DGVMTools_0.8.1.tar.gz’ had non-zero exit status

All the best,

**Comment by MagicForrest** [comment]
Hi Antony, thanks for reporting.

I think the issue should be fixed now, it was reproducible with R v3.6 on Windows and Ubuntu).  For posterity, it seems like R v3.6 doesn't like numeric vectors on the 'prototype' part of an S4 class definition.  That seems silly to me, but is easy enough to solve in this case.

Anyways, the master branch has been updated so go ahead and try your install again.  And if it works feel free to close the issue ;-).
