### ISSUE TITLE
Can´t extract yearly-GPP from Saatchi dataset with getField()

### ISSUE THREAD

**Issue by antonycastro** [MagicForrest/DGVMTools#28]
Hello,

I was trying to extract the yearly-GPP from Saatchi dataset using getField(). Unluckily, I get errors. Is strange because I can extract other variables. Here the code:

> Saatchi.vegC <- getField(source = Saatchi.dataset,
+                          var = "aGPP_std")
Error in R_nc4_open: No such file or directory
Error in ncdf4::nc_open(file.name.nc, readunlim = FALSE, verbose = verbose,  : 
  Error in nc_open trying to open file C:/Users/Tony/Documents/R/win-library/3.6/DGVMTools/extdata/DGVMData/Saatchi2011/HD/aGPP_std.nc

... You know how could I solve this?

All the best,

**Comment by MagicForrest** [comment]
See the email I just sent a second ago, but basically there is no GPP data in the Saatchi data.
