### ISSUE TITLE
ED2 outputs

### ISSUE THREAD

**Issue by ashiklom** [MagicForrest/DGVMTools#34]
Model source code: https://github.com/edmodel/ed2

For ideas on how to load this, see the [`PEcAn.ED2` package](https://github.com/PecanProject/pecan/tree/develop/models/ed), particularly the [`model2netcdf.ED2` function](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R). 

I have a lot of experience with processing outputs from this model, so I would be happy to open a PR for this at some point if this is of interest. A key challenge is that ED2 outputs have a configurable (i.e. not fixed) time-step, and that in many cases this time-step is subdaily.

**Comment by MagicForrest** [comment]
Hi Alexey,

I am happy that you are interested in this!  Given your experience with ED output, I think it makes more sense for you to open a PR.  In general, my preferred strategy is to have people who work regularly with a particular model handle the model specific code that loads model data.

Yes, DGVMTools is not currently compatible with subdaily data.  I think for the first pass just aggregating the data to daily, using an aggregate method passed in by "..." is probably a good way to go. 

But implementing sub-daily data is indeed something I can think about.

**Comment by MagicForrest** [comment]
Hi Alexey.  It has been a long time, but are you still interested in adding ED2 support to DGVMTools?  Right now I am just preparing a new release with new features.  Hopefully this is the penultimate release before CRAN and paper publication.  If you contributed ED2 support you would of course be a co-author on said paper ;-)

I haven't moved to subdaily yet (maybe you lost interest when you heard that) and amn't planning to do that in the near term (there has been no other demand for it).  

One thing I have been doing is generalising the netCDF reading capabilities which would probably be very helpful for such an endeavour.  

Anyways, let me know if you still interested.

**Comment by ashiklom** [comment]
Hi! Apologies for the long silence. Unfortunately, I'm quite swamped, so I probably won't be able to commit any time to this, and I definitely don't want to delay your publication! I do have a few ED2-related research grants pending, and if any of them get funded, I would be happy to spend some time (or direct a postdoc or intern) to adding ED2 functionality to DGVMTools.

**Comment by MagicForrest** [comment]
Okay, thanks for getting back to me.  I'll leave this issue open as general reminder, also perhaps to inspire other DGVMers to produce specific support for their models.

In related news, I have nearly finished a major upgrade of the NetCDF reading functionality (coming in v0.10).  This has two major implications:
* Firstly, a lot of DGVM/LSM output can be read directly with this machinery, especially if they stick closely to the CF standard for netCDF (and don't use rotated grids or other craziness).  This means model specific support might not be necessary for some models.  I am not sure this will work for ED2, but if you send me some example files I will happily test it out.
* Secondly, this new machinery is a very solid foundation for building model-specific reading code.  Even if the files read okay with the general netCDF reader, this approach can still add extra convenience for specific models (by automatically adding metadata about PFTs, C pools, etc).
