### ISSUE TITLE
writeNetCDF: (Option to) save entire Earth

### ISSUE THREAD

**Issue by samsrabin** [MagicForrest/DGVMTools#67]
As it is now, it seems that writeNetCDF only saves to its Lon and Lat variables values that are actually included somewhere in the dataset. This typically means that, even for a "global" DGVM run, the poles and Atlantic Ocean are excluded. While this might make sense from a space-saving perspective, it makes it difficult to work with the output files in other programs. Ideally, it would be possible to tell writeNetCDF to save a global map, filling unused space with the missing value.

[Here](https://www.dropbox.com/s/lxb442uwbisuto8/biomes_map.Smith2014.ssp5.2091-2100.nc?dl=0) is one such file as an example. When I import this into MATLAB, I get an array of size 277 lat, 695 lon. I thus have to do extra work to make it align with data from files that are actually global in extent.

**Comment by MagicForrest** [comment]
Hi Sam.  Good points you make there.  It should be possible to fill in the Atlantic, I recently adjusted that. Try the branch Format-NetCDF, it should automatically fills gaps in Lon and Lat when writing netCDFs.

As for truly "going global" that is something I should work on.  It wouldn't be too hard to expand the Lon and Lats to the globe.  I'll consider that an open issue that I should address in the next release.

**Comment by MagicForrest** [comment]
Implemented in branch "Format-NetCDF" for testing.  Should be included in release v0.10.
