### ISSUE TITLE
Vignette unavailable

### ISSUE THREAD

**Issue by teatree1212** [MagicForrest/DGVMTools#69]
Hi Matthew,

I am new to the DGVMTools package and wanted to explore the vignettes, which however seemed at first to be unavailable using two methods of installation.
First, after downloading the package from github using

```
devtools::install_github("MagicForrest/DGVMTools", ref = "master", dependencies = TRUE, build_opts = c("--no-resave-data", "--no-manual"), force=T)
```

, then using browseVignettes() and vignette() in Rstudio did not work:

```
> vignette("DGVMTools")
Warning message:
vignette ‘DGVMTools’ not found 


browseVignettes(package="DGVMTools")
No vignettes found by browseVignettes(package = "DGVMTools")
```
--

Then I tried manually cloning the repository and then installing using 

```
R CMD INSTALL DGVMTools
```
back in Rstudio and reloading DGVMTools gave me the same warning messages.

But I can see the vignettes in the folder vignetted in the uncompiled package and when using `open file.html` , I can get them to be displayed in my firefox browser.

I am using R version 4.0.5 (2021-03-31) -- "Shake and Throw" on Mac Big Sur 11.2.3 and devtools version 2.4.0

**Comment by MagicForrest** [comment]
Thanks for reporting!  I can reproduce this bug on my system and I have no idea why the vignettes are not accessible within R.  I'll look into it.  

But in your case it is not urgent because you have a workaround to access them, right?

**Comment by MagicForrest** [comment]
Okay, problem solved for the first case, one simply needs to add `build_vignettes = TRUE` to the devtools::install_github() command.    I have added this to he installation instructions in master branch.  It should work if you try out:

`devtools::install_github("MagicForrest/DGVMTools", ref = "master", dependencies = TRUE, build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE, force=T)`

Does that work for you?

The second case I will look at later...

**Comment by teatree1212** [comment]
that works well, thanks!
