### ISSUE TITLE
DGVMData not found

### ISSUE THREAD

**Issue by EstellepaleoR** [MagicForrest/DGVMTools#70]
Hi Matthew, 

I've been trying to compare my run with some available data such as the Biome model and always receives the error below: 

```
biomes.source <- defineSource(id = "DataBiomes",
   dir = system.file("extdata", "DGVMData", "HandP_PNV", "HD", package = "DGVMTools"), 
   format = DGVMData,
  name = "Haxeltine and Prentice Biomes")
```

Error in defineSource(id = "DataBiomes", dir = system.file("extdata",  : 
  object 'DGVMData' not found

Could you help me on how to fix this please? 
Thanks

**Comment by MagicForrest** [comment]
Hi Estelle, that is an easy one.  Just exchange "DGVMData" with "NetCDF" and it should work fine.

The reason for this happening is that I replaced the previous DGVMData Format (which was rather custom and inflexible) with a much more general NetCDF Format.  The NetCDF Format should be capable of reading a fairly wide range of netCDF files if they have a reasonably standard destruction (ie include longitude and latitide dimensions and have a time dimension with units which are not toooo crazy).

**Comment by EstellepaleoR** [comment]
Hi, 

Thank you so much for the quick reply Matthew. It is indeed working nicely. 
Should send you an email soon for more discussions on the outputs :)

Cheers

**Comment by MagicForrest** [comment]
Great!
