### ISSUE TITLE
Is it possible to eliminate the maptools dependency?

### ISSUE THREAD

**Issue by hol430** [MagicForrest/DGVMTools#86]
Hi Matt, the maptools package is currently in the process of being retired, and indeed was [removed from CRAN](https://cran.r-project.org/web/packages/maptools/index.html) a few days ago. How much work would it be to replace this dependency with something else? Would I be correct in guessing that it's used only for the spatial plots?

I'll admit that I haven't really looked into how it's used by this package; I only noticed this problem when trying to install the package on a new computer :).

**Comment by MagicForrest** [comment]
Hi Drew, that is already done in the dev-v1.1 branch!  Just switch to that and all should be well.

I will try to make a new release soon.

**Comment by hol430** [comment]
Ah, brilliant, thanks for that!

**Comment by MagicForrest** [comment]
... and merged into master for imminent release.
