### ISSUE TITLE
define new quantity seems to fail

### ISSUE THREAD

**Issue by anthoni-p** [MagicForrest/DGVMTools#94]
Hi Matt.
is there somethign wrong in the definition or handling of a new quantity in the code below?
yield.quant=DGVMTools::defineQuantity(id="yield",name="yield","kgDM/m^2/y")
GUESS.updated=DGVMTools::addTo(yield.quant,add.to = GUESS)
S0.sp500.src=defineSource("S0_sp500_luc1550","S0_sp500_luc1550"
                           ,dir="~/GCP/GCP_2023/tech_cfxinput_runs/S0_global_nspin500/output-2024-03-05/"
                           ,format=GUESS.updated)
yield.s0.sp500=getField(source = S0.sp500.src,quant="yield")
Error in getStandardQuantity_LPJ(source, quant, layers, target.sta = target.STAInfo,  : 
  Unfortunately standard quantity yield does not seem to be available in LPJ-GUESS

cheers
Peter

**Comment by MagicForrest** [comment]
Hmmm... try adding `"format" = "GUESS"`  to the `defineQuantity()` call.

**Comment by anthoni-p** [comment]
yep, 
yield.quant=DGVMTools::defineQuantity(id="yield",name="yield","kgDM/m^2/y",format="GUESS")
works, thanks
